---
title: "Spotify Listening"
format: dashboard
logo: "spotify.svg"
theme: 
  - style.scss
embed-resources: true
---

```{r Load scripts, echo=FALSE}
source("~/spotify_dashboard/scripts/00_load_and_clean.R", local = knitr::knit_global())
source("~/spotify_dashboard/scripts/01_analysis.R", local = knitr::knit_global())
source("~/spotify_dashboard/scripts/02_visuals.R", local = knitr::knit_global())
```


# 2019

## Row {height="20%"}

```{r Unique artists 2019, echo=FALSE}
#| component: valuebox
#| title: "Unique Artists"

list(
  icon = "music-player-fill",
  color = "#228B22",
  value = artists_19_count
)

```

```{r Unique tracks 2019, echo=FALSE}
#| component: valuebox
#| title: "Unique Tracks"

list(
  icon = "file-music-fill",
  color = "#2FF924",
  value = tracks_19_count
)

```

```{r Unique albums 2019, echo=FALSE}
#| component: valuebox
#| title: "Unique Albums"

list(
  icon = "vinyl-fill",
  color = "#98fb98",
  value = albums_19_count
)

```

## Row {.tabset height="80%"}

### Heatmap Calendar

```{r Heatmap 2019, echo=FALSE}
heat_2019
```


# 2020

## Row {height="20%"}

```{r Unique artists 2020, echo=FALSE}
#| component: valuebox
#| title: "Unique Artists"

list(
  icon = "music-player-fill",
  color = "#228B22",
  value = artists_20_count
)

```

```{r Unique tracks 2020, echo=FALSE}
#| component: valuebox
#| title: "Unique Tracks"

list(
  icon = "file-music-fill",
  color = "#2FF924",
  value = tracks_20_count
)

```

```{r Unique albums 2020, echo=FALSE}
#| component: valuebox
#| title: "Unique Albums"

list(
  icon = "vinyl-fill",
  color = "#98fb98",
  value = albums_20_count
)

```

## Row {.tabset height="80%"}

### Heatmap Calendar

```{r Heatmap 2020, echo=FALSE}
heat_2020
```

# 2021

## Row {height="20%"}

```{r Unique artists 2021, echo=FALSE}
#| component: valuebox
#| title: "Unique Artists"

list(
  icon = "music-player-fill",
  color = "#228B22",
  value = artists_21_count
)

```

```{r Unique tracks 2021, echo=FALSE}
#| component: valuebox
#| title: "Unique Tracks"

list(
  icon = "file-music-fill",
  color = "#2FF924",
  value = tracks_21_count
)

```

```{r Unique albums 2021, echo=FALSE}
#| component: valuebox
#| title: "Unique Albums"

list(
  icon = "vinyl-fill",
  color = "#98fb98",
  value = albums_21_count
)

```

## Row {.tabset height="80%"}

### Heatmap Calendar

```{r Heatmap 2021, echo=FALSE}
heat_2021
```

# 2022

## Row {height="20%"}

```{r Unique artists 2022, echo=FALSE}
#| component: valuebox
#| title: "Unique Artists"

list(
  icon = "music-player-fill",
  color = "#228B22",
  value = artists_22_count
)

```

```{r Unique tracks 2022, echo=FALSE}
#| component: valuebox
#| title: "Unique Tracks"

list(
  icon = "file-music-fill",
  color = "#2FF924",
  value = tracks_22_count
)

```

```{r Unique albums 2022, echo=FALSE}
#| component: valuebox
#| title: "Unique Albums"

list(
  icon = "vinyl-fill",
  color = "#98fb98",
  value = albums_22_count
)

```

## Row {.tabset height="80%"}

### Heatmap Calendar

```{r Heatmap 2022, echo=FALSE}
heat_2022
```

# 2023

## Row {height="20%"}

```{r Unique artists 2023, echo=FALSE}
#| component: valuebox
#| title: "Unique Artists"

list(
  icon = "music-player-fill",
  color = "#228B22",
  value = artists_23_count
)

```

```{r Unique tracks 2023, echo=FALSE}
#| component: valuebox
#| title: "Unique Tracks"

list(
  icon = "file-music-fill",
  color = "#2FF924",
  value = tracks_23_count
)

```

```{r Unique albums 2023, echo=FALSE}
#| component: valuebox
#| title: "Unique Albums"

list(
  icon = "vinyl-fill",
  color = "#98fb98",
  value = albums_23_count
)

```

## Row {.tabset height="80%"}

### Heatmap Calendar

```{r Heatmap 2023, echo=FALSE}
heat_2023
```